apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: patch-jobs-role
  namespace: default
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: patch-jobs-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-jobs-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
