# permissions for end users to view concourses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: concourse-viewer-role
rules:
- apiGroups:
  - deploy.concourse-ci.org
  resources:
  - concourses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.concourse-ci.org
  resources:
  - concourses/status
  verbs:
  - get
