apiVersion: deploy.concourse-ci.org/v1alpha1
kind: Concourse
metadata:
  name: concourse-sample
spec:
  image: concourse/concourse-rc:6.0.0-rc.11
  web:
    replicas: 1
    postgres:
      host: db
      port: 5432
      credentialsSecretName: psql-creds
      database: concourse
    clusterName: dev
  worker:
    replicas: 2
