apiVersion: deploy.concourse-ci.org/v1alpha1
kind: Concourse
metadata:
  name: concourse-sample
spec:
  web:
    replicas: 1
    postgres:
      host: db
      port: 5432
      credentialsSecretName: psql-creds
      database: concourse
    clusterName: dev
  worker:
    replicas: 2
